// Animation names
#define TWITCHERSTRONG_ANIM_DEFAULT 0
#define TWITCHERSTRONG_ANIM_STAND 1
#define TWITCHERSTRONG_ANIM_STAND2 2
#define TWITCHERSTRONG_ANIM_WALK 3
#define TWITCHERSTRONG_ANIM_RUN 4
#define TWITCHERSTRONG_ANIM_RUN2 5
#define TWITCHERSTRONG_ANIM_BACKPEDAL 6
#define TWITCHERSTRONG_ANIM_MELEE1 7
#define TWITCHERSTRONG_ANIM_MELEE2 8
#define TWITCHERSTRONG_ANIM_MELEE3 9
#define TWITCHERSTRONG_ANIM_WOUND 10
#define TWITCHERSTRONG_ANIM_DEATHFRONT 11
#define TWITCHERSTRONG_ANIM_DEATHBACK 12
#define TWITCHERSTRONG_ANIM_JUMP 13

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERSTRONG_COLLISION_BOX_DEFAULT 0
#define TWITCHERSTRONG_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERSTRONG_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERSTRONG_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
