// Animation names
#define INFERNALSPECTER_ANIM_DEFAULT 0
#define INFERNALSPECTER_ANIM_STAND 1
#define INFERNALSPECTER_ANIM_WALK 2
#define INFERNALSPECTER_ANIM_MELEE1 3
#define INFERNALSPECTER_ANIM_MELEE2 4
#define INFERNALSPECTER_ANIM_WOUND 5
#define INFERNALSPECTER_ANIM_DEATHFRONT 6
#define INFERNALSPECTER_ANIM_DEATHBACK 7
#define INFERNALSPECTER_ANIM_FIRE 8
#define INFERNALSPECTER_ANIM_JUMP 9
#define INFERNALSPECTER_ANIM_RUN 10

// Color names

// Patch names

// Names of collision boxes
#define INFERNALSPECTER_COLLISION_BOX_DEFAULT 0
#define INFERNALSPECTER_COLLISION_BOX_DEATHBOX_FRONT 1
#define INFERNALSPECTER_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define INFERNALSPECTER_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
