// Animation names
#define TWITCHERFEMALE2_ANIM_DEFAULT 0
#define TWITCHERFEMALE2_ANIM_STAND 1
#define TWITCHERFEMALE2_ANIM_STAND2 2
#define TWITCHERFEMALE2_ANIM_WALK 3
#define TWITCHERFEMALE2_ANIM_RUN 4
#define TWITCHERFEMALE2_ANIM_RUN2 5
#define TWITCHERFEMALE2_ANIM_BACKPEDAL 6
#define TWITCHERFEMALE2_ANIM_MELEE1 7
#define TWITCHERFEMALE2_ANIM_MELEE2 8
#define TWITCHERFEMALE2_ANIM_MELEE3 9
#define TWITCHERFEMALE2_ANIM_WOUND 10
#define TWITCHERFEMALE2_ANIM_DEATHFRONT 11
#define TWITCHERFEMALE2_ANIM_DEATHBACK 12
#define TWITCHERFEMALE2_ANIM_JUMP 13

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERFEMALE2_COLLISION_BOX_DEFAULT 0
#define TWITCHERFEMALE2_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERFEMALE2_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERFEMALE2_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
