// Animation names
#define TWITCHERBLADED2_ANIM_DEFAULT 0
#define TWITCHERBLADED2_ANIM_STAND 1
#define TWITCHERBLADED2_ANIM_WALK 2
#define TWITCHERBLADED2_ANIM_RUN 3
#define TWITCHERBLADED2_ANIM_MELEE1 4
#define TWITCHERBLADED2_ANIM_MELEE2 5
#define TWITCHERBLADED2_ANIM_WOUND 6
#define TWITCHERBLADED2_ANIM_DEATHFRONT 7
#define TWITCHERBLADED2_ANIM_DEATHBACK 8
#define TWITCHERBLADED2_ANIM_MELEE3 9
#define TWITCHERBLADED2_ANIM_LEAP 10
#define TWITCHERBLADED2_ANIM_CHARGE 11
#define TWITCHERBLADED2_ANIM_MELEE4 12
#define TWITCHERBLADED2_ANIM_SPIT 13
#define TWITCHERBLADED2_ANIM_STABNPCBACK 14
#define TWITCHERBLADED2_ANIM_BACKPEDAL 15

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBLADED2_COLLISION_BOX_DEFAULT 0
#define TWITCHERBLADED2_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERBLADED2_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define TWITCHERBLADED2_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
