// Animation names
#define TWITCHERMALE_ANIM_DEFAULT 0
#define TWITCHERMALE_ANIM_STAND 1
#define TWITCHERMALE_ANIM_STAND2 2
#define TWITCHERMALE_ANIM_WALK 3
#define TWITCHERMALE_ANIM_RUN 4
#define TWITCHERMALE_ANIM_RUN2 5
#define TWITCHERMALE_ANIM_BACKPEDAL 6
#define TWITCHERMALE_ANIM_MELEE1 7
#define TWITCHERMALE_ANIM_MELEE2 8
#define TWITCHERMALE_ANIM_MELEE3 9
#define TWITCHERMALE_ANIM_WOUND 10
#define TWITCHERMALE_ANIM_DEATHFRONT 11
#define TWITCHERMALE_ANIM_DEATHBACK 12
#define TWITCHERMALE_ANIM_JUMP 13

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERMALE_COLLISION_BOX_DEFAULT 0
#define TWITCHERMALE_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERMALE_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERMALE_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
