// Animation names
#define TWITCHERSHADOW_ANIM_DEFAULT 0
#define TWITCHERSHADOW_ANIM_STAND 1
#define TWITCHERSHADOW_ANIM_WALK 2
#define TWITCHERSHADOW_ANIM_RUN 3
#define TWITCHERSHADOW_ANIM_MELEE1 4
#define TWITCHERSHADOW_ANIM_MELEE2 5
#define TWITCHERSHADOW_ANIM_WOUND 6
#define TWITCHERSHADOW_ANIM_DEATHFRONT 7
#define TWITCHERSHADOW_ANIM_DEATHBACK 8
#define TWITCHERSHADOW_ANIM_JUMP 9

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERSHADOW_COLLISION_BOX_DEFAULT 0
#define TWITCHERSHADOW_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERSHADOW_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
