// Animation names
#define TWITCHERMALE3_ANIM_DEFAULT 0
#define TWITCHERMALE3_ANIM_STAND 1
#define TWITCHERMALE3_ANIM_WALK 2
#define TWITCHERMALE3_ANIM_RUN 3
#define TWITCHERMALE3_ANIM_MELEE1 4
#define TWITCHERMALE3_ANIM_MELEE2 5
#define TWITCHERMALE3_ANIM_WOUND 6
#define TWITCHERMALE3_ANIM_DEATHFRONT 7
#define TWITCHERMALE3_ANIM_DEATHBACK 8
#define TWITCHERMALE3_ANIM_LEAP 9

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERMALE3_COLLISION_BOX_DEFAULT 0
#define TWITCHERMALE3_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERMALE3_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
