// Animation names
#define TWITCHERSKINNED_ANIM_DEFAULT 0
#define TWITCHERSKINNED_ANIM_STAND 1
#define TWITCHERSKINNED_ANIM_STAND2 2
#define TWITCHERSKINNED_ANIM_WALK 3
#define TWITCHERSKINNED_ANIM_RUN 4
#define TWITCHERSKINNED_ANIM_RUN2 5
#define TWITCHERSKINNED_ANIM_BACKPEDAL 6
#define TWITCHERSKINNED_ANIM_MELEE1 7
#define TWITCHERSKINNED_ANIM_MELEE2 8
#define TWITCHERSKINNED_ANIM_MELEE3 9
#define TWITCHERSKINNED_ANIM_WOUND 10
#define TWITCHERSKINNED_ANIM_DEATHFRONT 11
#define TWITCHERSKINNED_ANIM_DEATHBACK 12
#define TWITCHERSKINNED_ANIM_JUMP 13
#define TWITCHERSKINNED_ANIM_BLOCK 14
#define TWITCHERSKINNED_ANIM_MELEE4 15
#define TWITCHERSKINNED_ANIM_STRAFERIGHT 16
#define TWITCHERSKINNED_ANIM_STRAFELEFT 17
#define TWITCHERSKINNED_ANIM_STRUGGLEFRONT 18
#define TWITCHERSKINNED_ANIM_STRUGGLEBACK 19
#define TWITCHERSKINNED_ANIM_RUN3 20
#define TWITCHERSKINNED_ANIM_COWER 21
#define TWITCHERSKINNED_ANIM_COWERSTOP 22
#define TWITCHERSKINNED_ANIM_RUN4 23

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERSKINNED_COLLISION_BOX_DEFAULT 0
#define TWITCHERSKINNED_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERSKINNED_COLLISION_BOX_DEATHBOX_BACK 2
#define TWITCHERSKINNED_COLLISION_BOX_COWER 3

// Names of hit boxes
#define TWITCHERSKINNED_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
