// Animation names
#define TWITCHERBLADED4_ANIM_DEFAULT 0
#define TWITCHERBLADED4_ANIM_STAND 1
#define TWITCHERBLADED4_ANIM_WALK 2
#define TWITCHERBLADED4_ANIM_RUN 3
#define TWITCHERBLADED4_ANIM_MELEE1 4
#define TWITCHERBLADED4_ANIM_MELEE2 5
#define TWITCHERBLADED4_ANIM_WOUND 6
#define TWITCHERBLADED4_ANIM_DEATHFRONT 7
#define TWITCHERBLADED4_ANIM_DEATHBACK 8
#define TWITCHERBLADED4_ANIM_MELEE3 9
#define TWITCHERBLADED4_ANIM_LEAP 10
#define TWITCHERBLADED4_ANIM_BACKPEDAL 11
#define TWITCHERBLADED4_ANIM_BLOCK1 12

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBLADED4_COLLISION_BOX_DEFAULT 0
#define TWITCHERBLADED4_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERBLADED4_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define TWITCHERBLADED4_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
