// Animation names
#define WASTERMALE_ANIM_DEFAULT 0
#define WASTERMALE_ANIM_STAND 1
#define WASTERMALE_ANIM_WALK 2
#define WASTERMALE_ANIM_RUN 3
#define WASTERMALE_ANIM_STANDSWORD 4
#define WASTERMALE_ANIM_WALKSWORD 5
#define WASTERMALE_ANIM_RUNSWORD 6
#define WASTERMALE_ANIM_WOUNDSWORD 7
#define WASTERMALE_ANIM_MELEE1 8
#define WASTERMALE_ANIM_DEATHFRONT 9
#define WASTERMALE_ANIM_DEATHBACK 10
#define WASTERMALE_ANIM_MELEE2 11
#define WASTERMALE_ANIM_MELEE3 12
#define WASTERMALE_ANIM_BLOCK1 13
#define WASTERMALE_ANIM_SWIMIDLE 14
#define WASTERMALE_ANIM_SWIMMOVE 15
#define WASTERMALE_ANIM_SWIMMELEE1 16
#define WASTERMALE_ANIM_SWIMMELEE2 17
#define WASTERMALE_ANIM_SWIMWOUND 18
#define WASTERMALE_ANIM_SWIMDEATH 19
#define WASTERMALE_ANIM_MELEE4 20
#define WASTERMALE_ANIM_JUMPSWORD 21
#define WASTERMALE_ANIM_BACKPEDAL 22
#define WASTERMALE_ANIM_MELEE5 23
#define WASTERMALE_ANIM_MELEE6 24
#define WASTERMALE_ANIM_BLOCK2 25
#define WASTERMALE_ANIM_BLOCK3 26

// Color names

// Patch names

// Names of collision boxes
#define WASTERMALE_COLLISION_BOX_DEFAULT 0
#define WASTERMALE_COLLISION_BOX_DEATHBOX_FRONT 1
#define WASTERMALE_COLLISION_BOX_DEATHBOX_BACK 2
#define WASTERMALE_COLLISION_BOX_SWIM_DEFAULT 3

// Names of hit boxes
#define WASTERMALE_HIT_BOX_PART_NAME 0

// Attaching position names
#define WASTERMALE_ATTACHMENT_SWORD 0
#define WASTERMALE_ATTACHMENT_KNIFE 1

// Sound names
