// Animation names
#define TWITCHERBLADED_ANIM_DEFAULT 0
#define TWITCHERBLADED_ANIM_STAND 1
#define TWITCHERBLADED_ANIM_STAND2 2
#define TWITCHERBLADED_ANIM_WALK 3
#define TWITCHERBLADED_ANIM_RUN 4
#define TWITCHERBLADED_ANIM_RUN2 5
#define TWITCHERBLADED_ANIM_BACKPEDAL 6
#define TWITCHERBLADED_ANIM_MELEE1 7
#define TWITCHERBLADED_ANIM_MELEE2 8
#define TWITCHERBLADED_ANIM_MELEE3 9
#define TWITCHERBLADED_ANIM_WOUND 10
#define TWITCHERBLADED_ANIM_DEATHFRONT 11
#define TWITCHERBLADED_ANIM_DEATHBACK 12
#define TWITCHERBLADED_ANIM_JUMP 13

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBLADED_COLLISION_BOX_DEFAULT 0
#define TWITCHERBLADED_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERBLADED_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERBLADED_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
