// Animation names
#define TWITCHERDISEASED_ANIM_DEFAULT 0
#define TWITCHERDISEASED_ANIM_STAND 1
#define TWITCHERDISEASED_ANIM_WALK 2
#define TWITCHERDISEASED_ANIM_BACKPEDAL 3
#define TWITCHERDISEASED_ANIM_MELEE1 4
#define TWITCHERDISEASED_ANIM_MELEE2 5
#define TWITCHERDISEASED_ANIM_WOUND 6
#define TWITCHERDISEASED_ANIM_DEATHFRONT 7
#define TWITCHERDISEASED_ANIM_DEATHBACK 8
#define TWITCHERDISEASED_ANIM_JUMP 9
#define TWITCHERDISEASED_ANIM_WALK2 10

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERDISEASED_COLLISION_BOX_DEFAULT 0
#define TWITCHERDISEASED_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERDISEASED_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERDISEASED_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
