// Animation names
#define TWITCHERBALD_ANIM_DEFAULT 0
#define TWITCHERBALD_ANIM_STAND 1
#define TWITCHERBALD_ANIM_STAND2 2
#define TWITCHERBALD_ANIM_WALK 3
#define TWITCHERBALD_ANIM_RUN 4
#define TWITCHERBALD_ANIM_RUN2 5
#define TWITCHERBALD_ANIM_BACKPEDAL 6
#define TWITCHERBALD_ANIM_MELEE1 7
#define TWITCHERBALD_ANIM_MELEE2 8
#define TWITCHERBALD_ANIM_MELEE3 9
#define TWITCHERBALD_ANIM_WOUND 10
#define TWITCHERBALD_ANIM_DEATHFRONT 11
#define TWITCHERBALD_ANIM_DEATHBACK 12
#define TWITCHERBALD_ANIM_JUMP 13

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBALD_COLLISION_BOX_DEFAULT 0
#define TWITCHERBALD_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERBALD_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERBALD_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
