// Animation names
#define TWITCHERFEMALE2_ANIM_DEFAULT 0
#define TWITCHERFEMALE2_ANIM_STAND 1
#define TWITCHERFEMALE2_ANIM_WALK 2
#define TWITCHERFEMALE2_ANIM_RUN 3
#define TWITCHERFEMALE2_ANIM_MELEE1 4
#define TWITCHERFEMALE2_ANIM_MELEE2 5
#define TWITCHERFEMALE2_ANIM_WOUND 6
#define TWITCHERFEMALE2_ANIM_DEATHFRONT 7
#define TWITCHERFEMALE2_ANIM_DEATHBACK 8
#define TWITCHERFEMALE2_ANIM_LEAP 9
#define TWITCHERFEMALE2_ANIM_MELEE3 10

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERFEMALE2_COLLISION_BOX_DEFAULT 0
#define TWITCHERFEMALE2_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERFEMALE2_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define TWITCHERFEMALE2_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
