// Animation names
#define TWITCHERBLADED_ANIM_DEFAULT 0
#define TWITCHERBLADED_ANIM_STAND 1
#define TWITCHERBLADED_ANIM_WALK 2
#define TWITCHERBLADED_ANIM_RUN 3
#define TWITCHERBLADED_ANIM_MELEE1 4
#define TWITCHERBLADED_ANIM_MELEE2 5
#define TWITCHERBLADED_ANIM_WOUND 6
#define TWITCHERBLADED_ANIM_DEATHFRONT 7
#define TWITCHERBLADED_ANIM_DEATHBACK 8
#define TWITCHERBLADED_ANIM_MELEE3 9
#define TWITCHERBLADED_ANIM_LEAP 10
#define TWITCHERBLADED_ANIM_CHARGE 11

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBLADED_COLLISION_BOX_DEFAULT 0
#define TWITCHERBLADED_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERBLADED_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
