// Animation names
#define TWITCHERSTRONG_ANIM_DEFAULT 0
#define TWITCHERSTRONG_ANIM_STAND 1
#define TWITCHERSTRONG_ANIM_WALK 2
#define TWITCHERSTRONG_ANIM_RUN 3
#define TWITCHERSTRONG_ANIM_MELEE1 4
#define TWITCHERSTRONG_ANIM_MELEE2 5
#define TWITCHERSTRONG_ANIM_WOUND 6
#define TWITCHERSTRONG_ANIM_DEATHFRONT 7
#define TWITCHERSTRONG_ANIM_DEATHBACK 8
#define TWITCHERSTRONG_ANIM_MELEE3 9
#define TWITCHERSTRONG_ANIM_LEAP 10

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERSTRONG_COLLISION_BOX_DEFAULT 0
#define TWITCHERSTRONG_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERSTRONG_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
