// Animation names
#define TWITCHERSKINNED_ANIM_DEFAULT 0
#define TWITCHERSKINNED_ANIM_STAND 1
#define TWITCHERSKINNED_ANIM_WALK 2
#define TWITCHERSKINNED_ANIM_RUN 3
#define TWITCHERSKINNED_ANIM_MELEE1 4
#define TWITCHERSKINNED_ANIM_MELEE2 5
#define TWITCHERSKINNED_ANIM_WOUND 6
#define TWITCHERSKINNED_ANIM_DEATHFRONT 7
#define TWITCHERSKINNED_ANIM_DEATHBACK 8
#define TWITCHERSKINNED_ANIM_LEAP 9
#define TWITCHERSKINNED_ANIM_BACKPEDAL 10
#define TWITCHERSKINNED_ANIM_BLOCK1 11
#define TWITCHERSKINNED_ANIM_STRAFELEFT 12
#define TWITCHERSKINNED_ANIM_STRAFERIGHT 13
#define TWITCHERSKINNED_ANIM_DEATHFRONT2 14

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERSKINNED_COLLISION_BOX_DEFAULT 0
#define TWITCHERSKINNED_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERSKINNED_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
