// Animation names
#define GNAWBEAST_ANIM_DEFAULT 0
#define GNAWBEAST_ANIM_STAND 1
#define GNAWBEAST_ANIM_WALK 2
#define GNAWBEAST_ANIM_RUN 3
#define GNAWBEAST_ANIM_BACKPEDAL 4
#define GNAWBEAST_ANIM_MELEE1 5
#define GNAWBEAST_ANIM_MELEE2 6
#define GNAWBEAST_ANIM_WOUND 7
#define GNAWBEAST_ANIM_DEATHFRONT 8
#define GNAWBEAST_ANIM_DEATHBACK 9
#define GNAWBEAST_ANIM_JUMP 10
#define GNAWBEAST_ANIM_MELEE3 11
#define GNAWBEAST_ANIM_RUN2 12
#define GNAWBEAST_ANIM_MELEE4 13
#define GNAWBEAST_ANIM_RUN3 14

// Color names

// Patch names

// Names of collision boxes
#define GNAWBEAST_COLLISION_BOX_DEFAULT 0
#define GNAWBEAST_COLLISION_BOX_DEATHBOX_FRONT 1
#define GNAWBEAST_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define GNAWBEAST_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
