// Animation names
#define METALPIPEVIEWMODEL_ANIM_DEFAULT 0
#define METALPIPEVIEWMODEL_ANIM_IDLE 1
#define METALPIPEVIEWMODEL_ANIM_LOWER 2
#define METALPIPEVIEWMODEL_ANIM_RAISE 3
#define METALPIPEVIEWMODEL_ANIM_ATTACK 4
#define METALPIPEVIEWMODEL_ANIM_BLOCKIDLE 5
#define METALPIPEVIEWMODEL_ANIM_BLOCKLOWER 6
#define METALPIPEVIEWMODEL_ANIM_BLOCKRAISE 7

// Color names

// Patch names

// Names of collision boxes
#define METALPIPEVIEWMODEL_COLLISION_BOX_PART_NAME 0

// Names of hit boxes
#define METALPIPEVIEWMODEL_HIT_BOX_PART_NAME 0

// Attaching position names
#define METALPIPEVIEWMODEL_ATTACHMENT_THEPIPE 0

// Sound names
