// Animation names
#define KOROTUPROK_ANIM_DEFAULT 0
#define KOROTUPROK_ANIM_STAND 1
#define KOROTUPROK_ANIM_WALK 2
#define KOROTUPROK_ANIM_RUN 3
#define KOROTUPROK_ANIM_MELEE1 4
#define KOROTUPROK_ANIM_MELEE2 5
#define KOROTUPROK_ANIM_WOUND 6
#define KOROTUPROK_ANIM_DEATHFRONT 7
#define KOROTUPROK_ANIM_DEATHBACK 8
#define KOROTUPROK_ANIM_LEAP 9
#define KOROTUPROK_ANIM_MELEE3 10

// Color names

// Patch names

// Names of collision boxes
#define KOROTUPROK_COLLISION_BOX_DEFAULT 0
#define KOROTUPROK_COLLISION_BOX_FRONTDEATH_BOX 1
#define KOROTUPROK_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define KOROTUPROK_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
