// Animation names
#define SHAMBLER2_ANIM_DEFAULT 0
#define SHAMBLER2_ANIM_STAND 1
#define SHAMBLER2_ANIM_WALK 2
#define SHAMBLER2_ANIM_RUN 3
#define SHAMBLER2_ANIM_BACKPEDAL 4
#define SHAMBLER2_ANIM_WOUND 5
#define SHAMBLER2_ANIM_MELEE1 6
#define SHAMBLER2_ANIM_MELEE2 7
#define SHAMBLER2_ANIM_DEATHFRONT 8
#define SHAMBLER2_ANIM_DEATHBACK 9
#define SHAMBLER2_ANIM_LEAP 10
#define SHAMBLER2_ANIM_GETUPFRONT 11
#define SHAMBLER2_ANIM_GETUPBACK 12
#define SHAMBLER2_ANIM_DEADFRONT 13
#define SHAMBLER2_ANIM_DEADBACK 14
#define SHAMBLER2_ANIM_SPIT 15
#define SHAMBLER2_ANIM_THROW1 16
#define SHAMBLER2_ANIM_THROW2 17
#define SHAMBLER2_ANIM_JUMP 18

// Color names

// Patch names

// Names of collision boxes
#define SHAMBLER2_COLLISION_BOX_DEFAULT 0
#define SHAMBLER2_COLLISION_BOX_FRONTDEATH_BOX 1
#define SHAMBLER2_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define SHAMBLER2_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
