// Animation names
#define BLACKSTICKMANTRANSLUCENT_ANIM_DEFAULT 0
#define BLACKSTICKMANTRANSLUCENT_ANIM_STAND 1
#define BLACKSTICKMANTRANSLUCENT_ANIM_WALK 2
#define BLACKSTICKMANTRANSLUCENT_ANIM_RUN 3
#define BLACKSTICKMANTRANSLUCENT_ANIM_FLY 4

// Color names

// Patch names

// Names of collision boxes
#define BLACKSTICKMANTRANSLUCENT_COLLISION_BOX_DEFAULT 0
#define BLACKSTICKMANTRANSLUCENT_COLLISION_BOX_DEATH_BOX 1

// Attaching position names

// Sound names
