// Animation names
#define BLACKSTICKMANREFLECTIVE_ANIM_DEFAULT 0
#define BLACKSTICKMANREFLECTIVE_ANIM_STAND 1
#define BLACKSTICKMANREFLECTIVE_ANIM_WALK 2
#define BLACKSTICKMANREFLECTIVE_ANIM_RUN 3
#define BLACKSTICKMANREFLECTIVE_ANIM_FLY 4

// Color names

// Patch names

// Names of collision boxes
#define BLACKSTICKMANREFLECTIVE_COLLISION_BOX_DEFAULT 0
#define BLACKSTICKMANREFLECTIVE_COLLISION_BOX_DEATH_BOX 1

// Attaching position names

// Sound names
