// Animation names
#define GUNMANBLADED_ANIM_DEFAULT 0
#define GUNMANBLADED_ANIM_STAND 1
#define GUNMANBLADED_ANIM_WALK 2
#define GUNMANBLADED_ANIM_WOUND 3
#define GUNMANBLADED_ANIM_DEATHFRONT 4
#define GUNMANBLADED_ANIM_DEATHBACK 5
#define GUNMANBLADED_ANIM_RUN 6
#define GUNMANBLADED_ANIM_MELEE1 7
#define GUNMANBLADED_ANIM_MELEE2 8
#define GUNMANBLADED_ANIM_JUMP 9
#define GUNMANBLADED_ANIM_BACKPEDAL 10
#define GUNMANBLADED_ANIM_WOUNDHEAD 11

// Color names

// Patch names

// Names of collision boxes
#define GUNMANBLADED_COLLISION_BOX_DEFAULT 0
#define GUNMANBLADED_COLLISION_BOX_FRONTDEATH_BOX 1
#define GUNMANBLADED_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define GUNMANBLADED_HIT_BOX_HEAD 0

// Attaching position names

// Sound names
