// Animation names
#define REDDEATH_ANIM_DEFAULT 0
#define REDDEATH_ANIM_STAND 1
#define REDDEATH_ANIM_WALK 2
#define REDDEATH_ANIM_RUN 3
#define REDDEATH_ANIM_WOUND 4
#define REDDEATH_ANIM_FRONTDEATH 5
#define REDDEATH_ANIM_MELEE1 6
#define REDDEATH_ANIM_MELEE2 7
#define REDDEATH_ANIM_BACKDEATH 8
#define REDDEATH_ANIM_LEAP 9
#define REDDEATH_ANIM_BANG1 10

// Color names

// Patch names

// Names of collision boxes
#define REDDEATH_COLLISION_BOX_DEFAULT 0
#define REDDEATH_COLLISION_BOX_DEATHBOX_FRONT 1
#define REDDEATH_COLLISION_BOX_DEATHBOX_BACK 2

// Attaching position names

// Sound names
