// Animation names
#define TWITCHERNIGHTMAREBLADED_ANIM_DEFAULT 0
#define TWITCHERNIGHTMAREBLADED_ANIM_STAND 1
#define TWITCHERNIGHTMAREBLADED_ANIM_STAND2 2
#define TWITCHERNIGHTMAREBLADED_ANIM_WALK 3
#define TWITCHERNIGHTMAREBLADED_ANIM_RUN 4
#define TWITCHERNIGHTMAREBLADED_ANIM_RUN2 5
#define TWITCHERNIGHTMAREBLADED_ANIM_BACKPEDAL 6
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE1 7
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE2 8
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE3 9
#define TWITCHERNIGHTMAREBLADED_ANIM_WOUND 10
#define TWITCHERNIGHTMAREBLADED_ANIM_DEATHFRONT 11
#define TWITCHERNIGHTMAREBLADED_ANIM_DEATHBACK 12
#define TWITCHERNIGHTMAREBLADED_ANIM_JUMP 13
#define TWITCHERNIGHTMAREBLADED_ANIM_BLOCK 14
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE4 15
#define TWITCHERNIGHTMAREBLADED_ANIM_STRAFELEFT 16
#define TWITCHERNIGHTMAREBLADED_ANIM_STRAFERIGHT 17
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE5 18
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE6 19
#define TWITCHERNIGHTMAREBLADED_ANIM_LEAPMELEE1 20
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE7 21
#define TWITCHERNIGHTMAREBLADED_ANIM_SPINMELEE1 22

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERNIGHTMAREBLADED_COLLISION_BOX_DEFAULT 0
#define TWITCHERNIGHTMAREBLADED_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERNIGHTMAREBLADED_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERNIGHTMAREBLADED_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
