// Animation names
#define TWITCHERBALD_ANIM_DEFAULT 0
#define TWITCHERBALD_ANIM_STAND 1
#define TWITCHERBALD_ANIM_WALK 2
#define TWITCHERBALD_ANIM_RUN 3
#define TWITCHERBALD_ANIM_MELEE1 4
#define TWITCHERBALD_ANIM_MELEE2 5
#define TWITCHERBALD_ANIM_WOUND 6
#define TWITCHERBALD_ANIM_DEATHFRONT 7
#define TWITCHERBALD_ANIM_DEATHBACK 8
#define TWITCHERBALD_ANIM_LEAP 9

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBALD_COLLISION_BOX_DEFAULT 0
#define TWITCHERBALD_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERBALD_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define TWITCHERBALD_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
