// Animation names
#define STRONGPISTOLVIEWMODEL_ANIM_DEFAULT 0
#define STRONGPISTOLVIEWMODEL_ANIM_IDLE 1
#define STRONGPISTOLVIEWMODEL_ANIM_RAISE 2
#define STRONGPISTOLVIEWMODEL_ANIM_LOWER 3
#define STRONGPISTOLVIEWMODEL_ANIM_FIRE 4

// Color names

// Patch names

// Names of collision boxes
#define STRONGPISTOLVIEWMODEL_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define STRONGPISTOLVIEWMODEL_ATTACHMENT_THEPISTOL 0

// Sound names
