// Animation names
#define PLANKVIEWMODEL_ANIM_DEFAULT 0
#define PLANKVIEWMODEL_ANIM_IDLE 1
#define PLANKVIEWMODEL_ANIM_LOWER 2
#define PLANKVIEWMODEL_ANIM_RAISE 3
#define PLANKVIEWMODEL_ANIM_ATTACK 4
#define PLANKVIEWMODEL_ANIM_ATTACK2 5
#define PLANKVIEWMODEL_ANIM_BLOCKIDLE 6
#define PLANKVIEWMODEL_ANIM_BLOCKLOWER 7
#define PLANKVIEWMODEL_ANIM_BLOCKRAISE 8
#define PLANKVIEWMODEL_ANIM_ATTACK3 9

// Color names

// Patch names

// Names of collision boxes
#define PLANKVIEWMODEL_COLLISION_BOX_PART_NAME 0

// Names of hit boxes
#define PLANKVIEWMODEL_HIT_BOX_PART_NAME 0

// Attaching position names
#define PLANKVIEWMODEL_ATTACHMENT_WOODENPLANK 0

// Sound names
