// Animation names
#define TWITCHERNIGHTMAREBLADED_ANIM_DEFAULT 0
#define TWITCHERNIGHTMAREBLADED_ANIM_STAND 1
#define TWITCHERNIGHTMAREBLADED_ANIM_WALK 2
#define TWITCHERNIGHTMAREBLADED_ANIM_RUN 3
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE1 4
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE2 5
#define TWITCHERNIGHTMAREBLADED_ANIM_WOUND 6
#define TWITCHERNIGHTMAREBLADED_ANIM_DEATHFRONT 7
#define TWITCHERNIGHTMAREBLADED_ANIM_DEATHBACK 8
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE3 9
#define TWITCHERNIGHTMAREBLADED_ANIM_JUMP 10
#define TWITCHERNIGHTMAREBLADED_ANIM_BACKPEDAL 11
#define TWITCHERNIGHTMAREBLADED_ANIM_BLOCK1 12
#define TWITCHERNIGHTMAREBLADED_ANIM_MELEE4 13
#define TWITCHERNIGHTMAREBLADED_ANIM_BLOCK2 14
#define TWITCHERNIGHTMAREBLADED_ANIM_SCRAPEPREPARE 15
#define TWITCHERNIGHTMAREBLADED_ANIM_WOUNDHEAD 16
#define TWITCHERNIGHTMAREBLADED_ANIM_STANDFIGHT 17

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERNIGHTMAREBLADED_COLLISION_BOX_DEFAULT 0
#define TWITCHERNIGHTMAREBLADED_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERNIGHTMAREBLADED_COLLISION_BOX_BACKDEATH_BOX 2

// Names of hit boxes
#define TWITCHERNIGHTMAREBLADED_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
