// Animation names
#define ABOMINATION_ANIM_DEFAULT 0
#define ABOMINATION_ANIM_STAND 1
#define ABOMINATION_ANIM_WALK 2
#define ABOMINATION_ANIM_MELEE 3
#define ABOMINATION_ANIM_DEATH 4
#define ABOMINATION_ANIM_WOUND 5
#define ABOMINATION_ANIM_SPIT 6
#define ABOMINATION_ANIM_CRAWL 7
#define ABOMINATION_ANIM_CROUCH 8
#define ABOMINATION_ANIM_RUN 9
#define ABOMINATION_ANIM_CHARGE 10
#define ABOMINATION_ANIM_SLAM 11
#define ABOMINATION_ANIM_STANDUP 12

// Color names

// Patch names

// Names of collision boxes
#define ABOMINATION_COLLISION_BOX_DEFAULT 0
#define ABOMINATION_COLLISION_BOX_DEATH_BOX 1

// Names of hit boxes
#define ABOMINATION_HIT_BOX_DEFAULT 0

// Attaching position names

// Sound names
