// Animation names
#define TWITCHERBLADED2_ANIM_DEFAULT 0
#define TWITCHERBLADED2_ANIM_STAND 1
#define TWITCHERBLADED2_ANIM_STAND2 2
#define TWITCHERBLADED2_ANIM_WALK 3
#define TWITCHERBLADED2_ANIM_RUN 4
#define TWITCHERBLADED2_ANIM_RUN2 5
#define TWITCHERBLADED2_ANIM_BACKPEDAL 6
#define TWITCHERBLADED2_ANIM_MELEE1 7
#define TWITCHERBLADED2_ANIM_MELEE2 8
#define TWITCHERBLADED2_ANIM_MELEE3 9
#define TWITCHERBLADED2_ANIM_WOUND 10
#define TWITCHERBLADED2_ANIM_DEATHFRONT 11
#define TWITCHERBLADED2_ANIM_DEATHBACK 12
#define TWITCHERBLADED2_ANIM_JUMP 13
#define TWITCHERBLADED2_ANIM_BLOCK 14
#define TWITCHERBLADED2_ANIM_SPIT 15
#define TWITCHERBLADED2_ANIM_MELEE4 16
#define TWITCHERBLADED2_ANIM_STRAFERIGHT 17
#define TWITCHERBLADED2_ANIM_STRAFELEFT 18

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERBLADED2_COLLISION_BOX_DEFAULT 0
#define TWITCHERBLADED2_COLLISION_BOX_DEATHBOX_FRONT 1
#define TWITCHERBLADED2_COLLISION_BOX_DEATHBOX_BACK 2

// Names of hit boxes
#define TWITCHERBLADED2_HIT_BOX_PART_NAME 0

// Attaching position names

// Sound names
