// Animation names
#define TWITCHERPALEBLADED_ANIM_DEFAULT 0
#define TWITCHERPALEBLADED_ANIM_STAND 1
#define TWITCHERPALEBLADED_ANIM_WALK 2
#define TWITCHERPALEBLADED_ANIM_RUN 3
#define TWITCHERPALEBLADED_ANIM_MELEE1 4
#define TWITCHERPALEBLADED_ANIM_MELEE2 5
#define TWITCHERPALEBLADED_ANIM_WOUND 6
#define TWITCHERPALEBLADED_ANIM_DEATHFRONT 7
#define TWITCHERPALEBLADED_ANIM_DEATHBACK 8
#define TWITCHERPALEBLADED_ANIM_MELEE3 9
#define TWITCHERPALEBLADED_ANIM_JUMP 10
#define TWITCHERPALEBLADED_ANIM_BACKPEDAL 11
#define TWITCHERPALEBLADED_ANIM_BLOCK1 12

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERPALEBLADED_COLLISION_BOX_DEFAULT 0
#define TWITCHERPALEBLADED_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERPALEBLADED_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
