// Animation names
#define TWITCHERFEMALE_ANIM_DEFAULT 0
#define TWITCHERFEMALE_ANIM_STAND 1
#define TWITCHERFEMALE_ANIM_WALK 2
#define TWITCHERFEMALE_ANIM_RUN 3
#define TWITCHERFEMALE_ANIM_MELEE1 4
#define TWITCHERFEMALE_ANIM_MELEE2 5
#define TWITCHERFEMALE_ANIM_WOUND 6
#define TWITCHERFEMALE_ANIM_DEATHFRONT 7
#define TWITCHERFEMALE_ANIM_DEATHBACK 8
#define TWITCHERFEMALE_ANIM_LEAP 9

// Color names

// Patch names

// Names of collision boxes
#define TWITCHERFEMALE_COLLISION_BOX_DEFAULT 0
#define TWITCHERFEMALE_COLLISION_BOX_FRONTDEATH_BOX 1
#define TWITCHERFEMALE_COLLISION_BOX_BACKDEATH_BOX 2

// Attaching position names

// Sound names
